### ISSUE TITLE
[Especial] Deixar a área de interesse visível todo o tempo

### ISSUE THREAD

**Issue by MariaGabrielaReis** [Equipe-Polaris-DSM-2021/web#29]
#### Qual o objetivo desta tarefa?
Assim que segurar o SHIFT para selecionar a área de interesse, deixar

Items a fazer:
- [x] Downgrade do leaflet - Não foi necessário, pois acabei arrumando o bug que acontecia no ImageOverlay que impedia a atualização do local da imagem
- [x] Implementação do leaflet-draw
- [x] Verificação de àrea selecionada - Validar antes de enviar a solicitação p/ backend

Melhorias:
- [x] Impedir usuário de selecionar duas areas de interesse
- [x] Melhorar estilo do bound de seleção

#### DoD
- [x] Revisão e integração
- [x] Documentação
- [ ] Critérios de aceitação atendidos (check do PO)
